#pragma once
#include <string>
#include <unordered_map>

enum class Operator
{
    Equals,
    NotEquals,
    EqualsStrict,
    NotEqualsStrict,
    Assign,
    Less,
    More,
    LessEq,
    MoreEq,
    Add,
    Sub,
    Mul,
    Div,
    AddAssign,
    SubAssign,
    MulAssign,
    DivAssign,
    ModuloAssign,
    Modulo,
    And,
    Or,
    Not,
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    BitLeftShift,
    BitRightShift,
    BitAndAssign,
    BitOrAssign,
    BitXorAssign,
    BitNotAssign,
    BitLeftShiftAssign,
    BitRightShiftAssign,
};

static const std::unordered_map<std::string, Operator> Operators = {
    {"===", Operator::EqualsStrict},
    {"==", Operator::Equals},
    {"!==", Operator::NotEqualsStrict},
    {"!=", Operator::NotEquals},
    {"!", Operator::Not},
    {"not", Operator::Not},
    {">=", Operator::MoreEq},
    {"<=", Operator::LessEq},
    {">>=", Operator::BitRightShiftAssign},
    {"<<=", Operator::BitLeftShiftAssign},
    {">>", Operator::BitRightShift},
    {"<<", Operator::BitRightShiftAssign},
    {"<", Operator::Less},
    {">", Operator::More},
    {"+=", Operator::AddAssign},
    {"-=", Operator::SubAssign},
    {"*=", Operator::MulAssign},
    {"/=", Operator::DivAssign},
    {"+", Operator::Add},
    {"-", Operator::Sub},
    {"*", Operator::Mul},
    {"/", Operator::Div},
    {"&&", Operator::And},
    {"||", Operator::Or},
    {"and", Operator::And},
    {"or", Operator::Or},
    {"&=", Operator::BitOrAssign},
    {"&=", Operator::BitAndAssign},
    {"~=", Operator::BitNotAssign},
    {"^=", Operator::BitXorAssign},
    {"%=", Operator::ModuloAssign},
    {"|", Operator::BitOrAssign},
    {"&", Operator::BitAndAssign},
    {"~", Operator::BitNotAssign},
    {"^", Operator::BitXorAssign},
    {"%", Operator::ModuloAssign},
};